site_name: ToolFront
site_description: ToolFront helps you retrieve information from large databases, APIs, and documents with AI.
site_url: https://toolfront.docs
repo_url: https://github.com/kruskal-labs/toolfront
repo_name: kruskal/toolfront

theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    # - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - announce.dismiss
    - navigation.tracking
    - navigation.prune

plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#3e8599"
        color: "#ffffff"
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: false
            show_bases: false
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_root_heading: true
            show_root_full_path: false


nav:
  - ToolFront: index.md
  - Getting Started:
    - Quickstart: getting_started/quickstart.md
    - FAQ: getting_started/faq.md
    - Community: getting_started/community.md
  - Documentation:
    - Databases:
      - documentation/databases/index.md
      - BigQuery: documentation/databases/bigquery.md
      - ClickHouse: documentation/databases/clickhouse.md
      - Databricks: documentation/databases/databricks.md
      - Druid: documentation/databases/druid.md
      - DuckDB: documentation/databases/duckdb.md
      - Flink: documentation/databases/flink.md
      - MSSQL: documentation/databases/mssql.md
      - MySQL: documentation/databases/mysql.md
      - Oracle: documentation/databases/oracle.md
      - PostgreSQL: documentation/databases/postgresql.md
      - PySpark: documentation/databases/pyspark.md
      - RisingWave: documentation/databases/risingwave.md
      - Snowflake: documentation/databases/snowflake.md
      - SQLite: documentation/databases/sqlite.md
      - Trino: documentation/databases/trino.md
    - APIs: documentation/api.md
    - Documents: documentation/document.md
    - AI Models:
      - documentation/ai_models/index.md
      - OpenAI: documentation/ai_models/openai.md
      - Anthropic: documentation/ai_models/anthropic.md
      - Google Gemini: documentation/ai_models/google.md
      - Groq: documentation/ai_models/groq.md
      - Mistral: documentation/ai_models/mistral.md
      - xAI (Grok): documentation/ai_models/xai.md
      - Cohere: documentation/ai_models/cohere.md
      - DeepSeek: documentation/ai_models/deepseek.md
      - AWS Bedrock: documentation/ai_models/bedrock.md
      - Azure OpenAI: documentation/ai_models/azure_openai.md
      - Hugging Face: documentation/ai_models/huggingface.md
      - Custom/Self-hosted: documentation/ai_models/custom.md
    - Structured Outputs: documentation/structured_outputs.md
  - API Reference:
    - Database: api_reference/database.md
    - API: api_reference/api.md
    - Document: api_reference/document.md
    - MCP: api_reference/mcp.md
  - Examples:
    - Overview: examples/index.md
    - Advanced: examples/advanced.md
    - APIs: examples/apis.md
    - Databases: examples/databases.md
    - Documents: examples/documents.md
    - Use Cases:
      - Databases:
        - Sales Analytics: examples/databases/sales_analytics.md
        - Customer Insights: examples/databases/customer_insights.md
        - Financial Reporting: examples/databases/financial_reporting.md
      - APIs:
        - Weather Data: examples/apis/weather_api.md
        - E-commerce Integration: examples/apis/ecommerce_api.md
        - Social Media Analytics: examples/apis/social_media_api.md
      - Documents:
        - Financial Reports: examples/documents/financial_reports.md
        - Research Papers: examples/documents/research_papers.md
        - Legal Contracts: examples/documents/legal_contracts.md    

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/css/custom.css
  - https://unpkg.com/aos@2.3.1/dist/aos.css

extra_javascript:
  - https://unpkg.com/aos@2.3.1/dist/aos.js
  - assets/js/marquee.js

extra:
  generator: false

copyright: Copyright &copy; 2025 Kruskal Labs, Inc.
