name: Test Suite

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main, master ]

jobs:
  unit-tests:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: useblacksmith/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run unit tests
      run: uv run pytest tests/unit/ -v --tb=short -x
    
    - name: Run linting
      run: uv run ruff check src/
    
    # - name: Check formatting
    #   run: uv run ruff format src/ tests/ --check

  integration-tests:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
          MYSQL_ROOT_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -P 3306 --protocol=TCP"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: TestPass123!
          MSSQL_PID: Express
        ports:
          - 1433:1433
        options: >-
          --health-cmd="/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P TestPass123! -C -Q 'SELECT 1'"
          --health-interval=30s
          --health-timeout=15s
          --health-retries=5
          --health-start-period=60s

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: useblacksmith/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.12
    
    - name: Install dependencies
      run: uv sync
    
    - name: Wait for databases
      run: |
        echo "Waiting for PostgreSQL..."
        timeout 60 bash -c 'until python3 -c "import socket; socket.create_connection((\"localhost\", 5432), timeout=1)" 2>/dev/null; do sleep 1; done'
        echo "Waiting for MySQL..."
        timeout 60 bash -c 'until python3 -c "import socket; socket.create_connection((\"localhost\", 3306), timeout=1)" 2>/dev/null; do sleep 1; done'
        echo "Waiting for SQL Server..."
        timeout 60 bash -c 'until python3 -c "import socket; socket.create_connection((\"localhost\", 1433), timeout=1)" 2>/dev/null; do sleep 1; done'
    
    - name: Run integration tests
      run: uv run pytest tests/integration/ -v --tb=short -x -m "not docker_compose"
      env:
        POSTGRES_URL: postgresql://testuser:testpass@localhost:5432/testdb
        MYSQL_URL: mysql://testuser:testpass@localhost:3306/testdb
        SQLSERVER_URL: mssql://sa:TestPass123!@localhost:1433/master
