name: Test Suite

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main, master ]

jobs:
  unit-tests:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: useblacksmith/setup-uv@v4
      with:
        version: "latest"
        
    - name: Create virtual environment
      run: uv venv
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: uv pip install -e ".[all]"
    
    - name: Run unit tests
      run: uv run pytest tests/unit/ -v --tb=short -x
    
    - name: Run linting
      run: uv run ruff check src/ --no-fix
    
    - name: Check formatting
      run: uv run ruff format src/ tests/ --check

